CREATE TABLE Admin (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  user_id VARCHAR(50) NOT NULL,
  phone BIGINT NOT NULL,
  company VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Employee (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  admin_id INT NOT NULL REFERENCES Admin(id)
);

CREATE TABLE Stress (
  id SERIAL PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES Employee(id),
  stress_level INT NOT NULL,
  datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);